language: node_js
node_js:
  - 0.10
env:
  global:
    - secure: "gvXZTqGB3LBMq+KqwMa7gTyvJ16ycC8PyDGbBDZuuE145pIiAgApAXCOZTggPRxEQVn97eqdH6BnQ6xL5yIHNu7KXNTijg6pdE8YUUExDS7aCWHPhFRirkXsKdkpxbxrP76gJLEL8rCBBZ4AQYzlYOB0JfLAi3nB3GLcDZyRqRc="
    - secure: "fHQQ6jeigqGW65cE8gpa1QQo6QHPzyjynYLdkcocGb6Tcqo9id68+VXhqaW8H83wIT4Rg4e8Gz34JOMuFwu+G6W6z8NU07dMcvBdumAgWOng5BgdzP8Eiy0OiA9wDreOamMOi+bZp+tmAmksLbQqv5WjCipGsneOcDrFjKR03cw="
    - SAUCE_CONNECT_READY_FILE=/tmp/sauce-connect-ready
before_install:
  - make bootstrap
script:
  - make test-ci
  - ./node_modules/.bin/lcov-result-merger "coverage/**/lcov.info" | ./node_modules/.bin/coveralls
